
version: "3"

services:
  redis:
    image: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    networks:
      - network
    restart: always  
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: "cmpe172"
    restart: always
  gumball:
    image: spring-gumball
    platform: linux/amd64
    depends_on:
      - mysql
    networks:
      - network
    ports:
      - 8080
    environment:
      MYSQL_HOST: "mysql"
      REDIS_HOST: "redis"
    restart: always
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - gumball
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "gumball"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

